services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:  streamlit-app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      # Aca se agregan tambien las variables adicionales como API Keys, Databases, etc
      # - DATABASE_URL=postrgresql://user:pass@host:5432.db
    expose:
      - "8501" # Aca estamos exponiendo dentro de la red, no a host
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "8080:80"
      # - "443:443" en el caso de querer habilitar https 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - /nginx/ssl:/etc/nginx/ssl:ro # para certificados si usamos TLS
      # - /nginx/logs:/var/log/nginx # esto es opcional para logs
    depends_on:
      - streamlit-app
    restart: unless-stopped

networks:
  default:
    name: streamlit_net


  